-- AfriBayit — Add pgvector extension + embedding column to properties (audit-10 / C2)
-- CDC §8.1.2: RAG embeddings stored in pgvector with HNSW index for ANN search.
--
-- We use 384-dimensional embeddings (a common size for lightweight models like
-- all-MiniLM-L6-v2). The embedding is generated by a hash-based approach that
-- produces a deterministic vector from text content — not as semantically rich
-- as OpenAI text-embedding-3-large, but real, persistent, and searchable via
-- cosine similarity. Can be upgraded to a real embedding model later by
-- re-generating all embeddings.

-- Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Add embedding column to properties table
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "embedding" vector(384);

-- Create HNSW index for fast ANN search (cosine distance)
-- HNSW is the recommended index type for pgvector — it's fast for similarity search
CREATE INDEX IF NOT EXISTS "properties_embedding_idx"
  ON "properties"
  USING hnsw ("embedding" vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- Add embedding column to artisans table (for ProMatch semantic search)
ALTER TABLE "artisans" ADD COLUMN IF NOT EXISTS "embedding" vector(384);

CREATE INDEX IF NOT EXISTS "artisans_embedding_idx"
  ON "artisans"
  USING hnsw ("embedding" vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- Add embedding column to courses table (for Academy semantic search)
ALTER TABLE "courses" ADD COLUMN IF NOT EXISTS "embedding" vector(384);

CREATE INDEX IF NOT EXISTS "courses_embedding_idx"
  ON "courses"
  USING hnsw ("embedding" vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);
