-- AfriBayit — Wave 3 DB Hardening Migration (auto-generated from actual schema)

BEGIN;

-- 1. Float → DECIMAL(19,4) for money columns
ALTER TABLE "ambassador_commissions" ALTER COLUMN "amount" TYPE DECIMAL(19,4) USING "amount"::DECIMAL(19,4);
ALTER TABLE "ambassadors" ALTER COLUMN "totalEarnings" TYPE DECIMAL(19,4) USING "totalEarnings"::DECIMAL(19,4);
ALTER TABLE "artisan_quotes" ALTER COLUMN "estimatedBudget" TYPE DECIMAL(19,4) USING "estimatedBudget"::DECIMAL(19,4);
ALTER TABLE "artisan_quotes" ALTER COLUMN "quotedPrice" TYPE DECIMAL(19,4) USING "quotedPrice"::DECIMAL(19,4);
ALTER TABLE "artisan_services" ALTER COLUMN "basePrice" TYPE DECIMAL(19,4) USING "basePrice"::DECIMAL(19,4);
ALTER TABLE "artisans" ALTER COLUMN "dailyRate" TYPE DECIMAL(19,4) USING "dailyRate"::DECIMAL(19,4);
ALTER TABLE "courses" ALTER COLUMN "price" TYPE DECIMAL(19,4) USING "price"::DECIMAL(19,4);
ALTER TABLE "disputes" ALTER COLUMN "resolutionAmount" TYPE DECIMAL(19,4) USING "resolutionAmount"::DECIMAL(19,4);
ALTER TABLE "escrow_accounts" ALTER COLUMN "balance" TYPE DECIMAL(19,4) USING "balance"::DECIMAL(19,4);
ALTER TABLE "escrow_accounts" ALTER COLUMN "heldAmount" TYPE DECIMAL(19,4) USING "heldAmount"::DECIMAL(19,4);
ALTER TABLE "escrow_accounts" ALTER COLUMN "refundedAmount" TYPE DECIMAL(19,4) USING "refundedAmount"::DECIMAL(19,4);
ALTER TABLE "escrow_accounts" ALTER COLUMN "releasedAmount" TYPE DECIMAL(19,4) USING "releasedAmount"::DECIMAL(19,4);
ALTER TABLE "escrow_ledger" ALTER COLUMN "amount" TYPE DECIMAL(19,4) USING "amount"::DECIMAL(19,4);
ALTER TABLE "escrow_ledger" ALTER COLUMN "balanceAfter" TYPE DECIMAL(19,4) USING "balanceAfter"::DECIMAL(19,4);
ALTER TABLE "geo_inspections" ALTER COLUMN "price" TYPE DECIMAL(19,4) USING "price"::DECIMAL(19,4);
ALTER TABLE "geometer_missions" ALTER COLUMN "price" TYPE DECIMAL(19,4) USING "price"::DECIMAL(19,4);
ALTER TABLE "guesthouse_bookings" ALTER COLUMN "totalPrice" TYPE DECIMAL(19,4) USING "totalPrice"::DECIMAL(19,4);
ALTER TABLE "guesthouse_meals" ALTER COLUMN "price" TYPE DECIMAL(19,4) USING "price"::DECIMAL(19,4);
ALTER TABLE "guesthouse_rooms" ALTER COLUMN "basePrice" TYPE DECIMAL(19,4) USING "basePrice"::DECIMAL(19,4);
ALTER TABLE "guesthouses" ALTER COLUMN "breakfastPrice" TYPE DECIMAL(19,4) USING "breakfastPrice"::DECIMAL(19,4);
ALTER TABLE "hotel_bookings" ALTER COLUMN "totalPrice" TYPE DECIMAL(19,4) USING "totalPrice"::DECIMAL(19,4);
ALTER TABLE "hotel_rooms" ALTER COLUMN "basePriceXof" TYPE DECIMAL(19,4) USING "basePriceXof"::DECIMAL(19,4);
ALTER TABLE "hotels" ALTER COLUMN "pricePerNight" TYPE DECIMAL(19,4) USING "pricePerNight"::DECIMAL(19,4);
ALTER TABLE "properties" ALTER COLUMN "price" TYPE DECIMAL(19,4) USING "price"::DECIMAL(19,4);
ALTER TABLE "room_availability" ALTER COLUMN "priceOverride" TYPE DECIMAL(19,4) USING "priceOverride"::DECIMAL(19,4);
ALTER TABLE "scheduled_payouts" ALTER COLUMN "amount" TYPE DECIMAL(19,4) USING "amount"::DECIMAL(19,4);
ALTER TABLE "short_term_rental_availability" ALTER COLUMN "priceOverride" TYPE DECIMAL(19,4) USING "priceOverride"::DECIMAL(19,4);
ALTER TABLE "short_term_rental_bookings" ALTER COLUMN "cleaningFee" TYPE DECIMAL(19,4) USING "cleaningFee"::DECIMAL(19,4);
ALTER TABLE "short_term_rental_bookings" ALTER COLUMN "pricePerNight" TYPE DECIMAL(19,4) USING "pricePerNight"::DECIMAL(19,4);
ALTER TABLE "short_term_rental_bookings" ALTER COLUMN "securityDeposit" TYPE DECIMAL(19,4) USING "securityDeposit"::DECIMAL(19,4);
ALTER TABLE "short_term_rental_bookings" ALTER COLUMN "serviceFee" TYPE DECIMAL(19,4) USING "serviceFee"::DECIMAL(19,4);
ALTER TABLE "short_term_rental_bookings" ALTER COLUMN "totalPrice" TYPE DECIMAL(19,4) USING "totalPrice"::DECIMAL(19,4);
ALTER TABLE "short_term_rentals" ALTER COLUMN "cleaningFee" TYPE DECIMAL(19,4) USING "cleaningFee"::DECIMAL(19,4);
ALTER TABLE "short_term_rentals" ALTER COLUMN "monthlyPrice" TYPE DECIMAL(19,4) USING "monthlyPrice"::DECIMAL(19,4);
ALTER TABLE "short_term_rentals" ALTER COLUMN "pricePerNight" TYPE DECIMAL(19,4) USING "pricePerNight"::DECIMAL(19,4);
ALTER TABLE "short_term_rentals" ALTER COLUMN "securityDeposit" TYPE DECIMAL(19,4) USING "securityDeposit"::DECIMAL(19,4);
ALTER TABLE "short_term_rentals" ALTER COLUMN "weeklyPrice" TYPE DECIMAL(19,4) USING "weeklyPrice"::DECIMAL(19,4);
ALTER TABLE "subscriptions" ALTER COLUMN "priceXof" TYPE DECIMAL(19,4) USING "priceXof"::DECIMAL(19,4);
ALTER TABLE "transactions" ALTER COLUMN "amount" TYPE DECIMAL(19,4) USING "amount"::DECIMAL(19,4);
ALTER TABLE "transactions" ALTER COLUMN "commission" TYPE DECIMAL(19,4) USING "commission"::DECIMAL(19,4);
ALTER TABLE "wallet_transactions" ALTER COLUMN "amount" TYPE DECIMAL(19,4) USING "amount"::DECIMAL(19,4);
ALTER TABLE "wallet_transactions" ALTER COLUMN "balanceAfter" TYPE DECIMAL(19,4) USING "balanceAfter"::DECIMAL(19,4);

-- 2. Float → DECIMAL(5,4) for rate columns
ALTER TABLE "agent_listings" ALTER COLUMN "boostLevel" TYPE DECIMAL(5,4) USING "boostLevel"::DECIMAL(5,4);
ALTER TABLE "ambassador_commissions" ALTER COLUMN "commissionRate" TYPE DECIMAL(5,4) USING "commissionRate"::DECIMAL(5,4);
ALTER TABLE "ambassadors" ALTER COLUMN "commissionRate" TYPE DECIMAL(5,4) USING "commissionRate"::DECIMAL(5,4);
ALTER TABLE "guesthouse_pricing_rules" ALTER COLUMN "multiplier" TYPE DECIMAL(5,4) USING "multiplier"::DECIMAL(5,4);
ALTER TABLE "short_term_rental_pricing_rules" ALTER COLUMN "multiplier" TYPE DECIMAL(5,4) USING "multiplier"::DECIMAL(5,4);
ALTER TABLE "transactions" ALTER COLUMN "commissionRate" TYPE DECIMAL(5,4) USING "commissionRate"::DECIMAL(5,4);

-- 3. TEXT → JSONB for JSON-stored columns
ALTER TABLE "afripoint_transactions" ALTER COLUMN "metadata" TYPE JSONB USING NULLIF("metadata", '')::jsonb;
ALTER TABLE "artisans" ALTER COLUMN "portfolio" TYPE JSONB USING NULLIF("portfolio", '')::jsonb;
ALTER TABLE "artisans" ALTER COLUMN "specialties" TYPE JSONB USING NULLIF("specialties", '')::jsonb;
ALTER TABLE "audit_logs" ALTER COLUMN "details" TYPE JSONB USING NULLIF("details", '')::jsonb;
ALTER TABLE "chat_messages" ALTER COLUMN "metadata" TYPE JSONB USING NULLIF("metadata", '')::jsonb;
ALTER TABLE "community_posts" ALTER COLUMN "tags" TYPE JSONB USING NULLIF("tags", '')::jsonb;
ALTER TABLE "conversations" ALTER COLUMN "metadata" TYPE JSONB USING NULLIF("metadata", '')::jsonb;
ALTER TABLE "course_enrollments" ALTER COLUMN "completedModules" TYPE JSONB USING NULLIF("completedModules", '')::jsonb;
ALTER TABLE "courses" ALTER COLUMN "modules" TYPE JSONB USING NULLIF("modules", '')::jsonb;
ALTER TABLE "disputes" ALTER COLUMN "evidenceUrls" TYPE JSONB USING NULLIF("evidenceUrls", '')::jsonb;
ALTER TABLE "escrow_ledger" ALTER COLUMN "metadata" TYPE JSONB USING NULLIF("metadata", '')::jsonb;
ALTER TABLE "geometers" ALTER COLUMN "specialities" TYPE JSONB USING NULLIF("specialities", '')::jsonb;
ALTER TABLE "guesthouse_meals" ALTER COLUMN "availableForRoom" TYPE JSONB USING NULLIF("availableForRoom", '')::jsonb;
ALTER TABLE "guesthouse_rooms" ALTER COLUMN "amenities" TYPE JSONB USING NULLIF("amenities", '')::jsonb;
ALTER TABLE "guesthouse_rooms" ALTER COLUMN "photos" TYPE JSONB USING NULLIF("photos", '')::jsonb;
ALTER TABLE "guesthouse_staff" ALTER COLUMN "schedule" TYPE JSONB USING NULLIF("schedule", '')::jsonb;
ALTER TABLE "guesthouses" ALTER COLUMN "amenities" TYPE JSONB USING NULLIF("amenities", '')::jsonb;
ALTER TABLE "guesthouses" ALTER COLUMN "images" TYPE JSONB USING NULLIF("images", '')::jsonb;
ALTER TABLE "guesthouses" ALTER COLUMN "rules" TYPE JSONB USING NULLIF("rules", '')::jsonb;
ALTER TABLE "hotel_rooms" ALTER COLUMN "amenities" TYPE JSONB USING NULLIF("amenities", '')::jsonb;
ALTER TABLE "hotel_rooms" ALTER COLUMN "photos" TYPE JSONB USING NULLIF("photos", '')::jsonb;
ALTER TABLE "hotels" ALTER COLUMN "amenities" TYPE JSONB USING NULLIF("amenities", '')::jsonb;
ALTER TABLE "hotels" ALTER COLUMN "images" TYPE JSONB USING NULLIF("images", '')::jsonb;
ALTER TABLE "hotels" ALTER COLUMN "otaRefs" TYPE JSONB USING NULLIF("otaRefs", '')::jsonb;
ALTER TABLE "hotels" ALTER COLUMN "policies" TYPE JSONB USING NULLIF("policies", '')::jsonb;
ALTER TABLE "kyc_documents" ALTER COLUMN "ocrResult" TYPE JSONB USING NULLIF("ocrResult", '')::jsonb;
ALTER TABLE "notifications" ALTER COLUMN "channels" TYPE JSONB USING NULLIF("channels", '')::jsonb;
ALTER TABLE "notifications" ALTER COLUMN "metadata" TYPE JSONB USING NULLIF("metadata", '')::jsonb;
ALTER TABLE "notifications" ALTER COLUMN "sentVia" TYPE JSONB USING NULLIF("sentVia", '')::jsonb;
ALTER TABLE "ota_sync_logs" ALTER COLUMN "payload" TYPE JSONB USING NULLIF("payload", '')::jsonb;
ALTER TABLE "professional_profiles" ALTER COLUMN "certifications" TYPE JSONB USING NULLIF("certifications", '')::jsonb;
ALTER TABLE "professional_profiles" ALTER COLUMN "education" TYPE JSONB USING NULLIF("education", '')::jsonb;
ALTER TABLE "professional_profiles" ALTER COLUMN "experience" TYPE JSONB USING NULLIF("experience", '')::jsonb;
ALTER TABLE "professional_profiles" ALTER COLUMN "languages" TYPE JSONB USING NULLIF("languages", '')::jsonb;
ALTER TABLE "professional_profiles" ALTER COLUMN "portfolio" TYPE JSONB USING NULLIF("portfolio", '')::jsonb;
ALTER TABLE "professional_profiles" ALTER COLUMN "specialities" TYPE JSONB USING NULLIF("specialities", '')::jsonb;
ALTER TABLE "properties" ALTER COLUMN "features" TYPE JSONB USING NULLIF("features", '')::jsonb;
ALTER TABLE "properties" ALTER COLUMN "images" TYPE JSONB USING NULLIF("images", '')::jsonb;
ALTER TABLE "property_legal_docs" ALTER COLUMN "ocrResult" TYPE JSONB USING NULLIF("ocrResult", '')::jsonb;
ALTER TABLE "reviews" ALTER COLUMN "subRatings" TYPE JSONB USING NULLIF("subRatings", '')::jsonb;
ALTER TABLE "scheduled_payouts" ALTER COLUMN "metadata" TYPE JSONB USING NULLIF("metadata", '')::jsonb;
ALTER TABLE "short_term_rentals" ALTER COLUMN "amenities" TYPE JSONB USING NULLIF("amenities", '')::jsonb;
ALTER TABLE "short_term_rentals" ALTER COLUMN "houseRules" TYPE JSONB USING NULLIF("houseRules", '')::jsonb;
ALTER TABLE "short_term_rentals" ALTER COLUMN "images" TYPE JSONB USING NULLIF("images", '')::jsonb;
ALTER TABLE "short_term_rentals" ALTER COLUMN "otaRefs" TYPE JSONB USING NULLIF("otaRefs", '')::jsonb;
ALTER TABLE "short_term_rentals" ALTER COLUMN "otaSyncStatus" TYPE JSONB USING NULLIF("otaSyncStatus", '')::jsonb;
ALTER TABLE "transaction_timeline" ALTER COLUMN "metadata" TYPE JSONB USING NULLIF("metadata", '')::jsonb;
ALTER TABLE "transactions" ALTER COLUMN "conditions" TYPE JSONB USING NULLIF("conditions", '')::jsonb;
ALTER TABLE "transactions" ALTER COLUMN "ledgerEntries" TYPE JSONB USING NULLIF("ledgerEntries", '')::jsonb;
ALTER TABLE "users" ALTER COLUMN "notificationPreferences" TYPE JSONB USING NULLIF("notificationPreferences", '')::jsonb;
ALTER TABLE "users" ALTER COLUMN "specialties" TYPE JSONB USING NULLIF("specialties", '')::jsonb;
ALTER TABLE "wallet_transactions" ALTER COLUMN "metadata" TYPE JSONB USING NULLIF("metadata", '')::jsonb;
ALTER TABLE "webhook_events" ALTER COLUMN "payload" TYPE JSONB USING NULLIF("payload", '')::jsonb;

-- 4. Add country to wallet_transactions + RLS
ALTER TABLE "wallet_transactions" ADD COLUMN IF NOT EXISTS "country" TEXT;
UPDATE "wallet_transactions" wt SET "country" = u."country" FROM "users" u WHERE wt."userId" = u."id" AND wt."country" IS NULL;
CREATE INDEX IF NOT EXISTS "wallet_transactions_country_idx" ON "wallet_transactions" ("country");
ALTER TABLE "wallet_transactions" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "wallet_transactions_country_isolation" ON "wallet_transactions";
CREATE POLICY "wallet_transactions_country_isolation" ON "wallet_transactions" USING ("country" = current_setting('app.current_country', true) OR current_setting('app.current_country', true) = 'NONE' OR current_setting('app.current_country', true) IS NULL);

-- 5. Add deletedAt soft-delete columns
ALTER TABLE "properties" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "property_images" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "property_legal_docs" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "virtual_tours" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "transactions" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "escrow_accounts" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "escrow_ledger" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "transaction_timeline" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "wallet_transactions" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "hotels" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "hotel_bookings" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "hotel_reviews" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "guesthouses" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "guesthouse_bookings" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "guesthouse_rooms" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "short_term_rentals" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "short_term_rental_bookings" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "artisans" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "artisan_services" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "artisan_quotes" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "courses" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "course_enrollments" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "community_posts" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "community_replies" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "community_groups" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "community_events" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "notaries" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "notifications" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "kyc_documents" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "professional_profiles" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "ambassadors" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "subscriptions" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);

-- 6. Add missing indexes
CREATE INDEX IF NOT EXISTS "PropertyImage_propertyId_idx" ON "property_images" ("propertyId");
CREATE INDEX IF NOT EXISTS "VirtualTour_propertyId_idx" ON "virtual_tours" ("propertyId");
CREATE INDEX IF NOT EXISTS "PropertyLegalDoc_propertyId_idx" ON "property_legal_docs" ("propertyId");
CREATE INDEX IF NOT EXISTS "AgentListing_propertyId_idx" ON "agent_listings" ("propertyId");
CREATE INDEX IF NOT EXISTS "Review_target_idx" ON "reviews" ("targetType", "targetId");
CREATE INDEX IF NOT EXISTS "EscrowLedger_escrowAccountId_idx" ON "escrow_ledger" ("escrowAccountId");
CREATE INDEX IF NOT EXISTS "TransactionTimeline_transactionId_idx" ON "transaction_timeline" ("transactionId");
CREATE INDEX IF NOT EXISTS "WalletTransaction_userId_idx" ON "wallet_transactions" ("userId");
CREATE INDEX IF NOT EXISTS "HotelBooking_userId_idx" ON "hotel_bookings" ("userId");
CREATE INDEX IF NOT EXISTS "HotelBooking_hotel_checkIn_idx" ON "hotel_bookings" ("hotelId", "checkIn");
CREATE INDEX IF NOT EXISTS "GuesthouseBooking_checkIn_idx" ON "guesthouse_bookings" ("guesthouseId", "checkIn");
CREATE INDEX IF NOT EXISTS "ShortTermRentalBooking_checkIn_idx" ON "short_term_rental_bookings" ("rentalId", "checkIn");
CREATE INDEX IF NOT EXISTS "CommunityPost_authorId_idx" ON "community_posts" ("authorId");
CREATE INDEX IF NOT EXISTS "CommunityReply_postId_idx" ON "community_replies" ("postId");
CREATE INDEX IF NOT EXISTS "Certificate_user_course_idx" ON "certificates" ("userId", "courseId");
CREATE INDEX IF NOT EXISTS "GeometerMission_geometerId_idx" ON "geometer_missions" ("geometerId");
CREATE INDEX IF NOT EXISTS "ChatMessage_conversationId_idx" ON "chat_messages" ("conversationId");
CREATE INDEX IF NOT EXISTS "Notification_user_read_idx" ON "notifications" ("userId", "read");
CREATE INDEX IF NOT EXISTS "SavedSearch_userId_idx" ON "saved_searches" ("userId");
CREATE INDEX IF NOT EXISTS "PriceAlert_userId_idx" ON "price_alerts" ("userId");
CREATE INDEX IF NOT EXISTS "Favorite_userId_idx" ON "favorites" ("userId");
CREATE INDEX IF NOT EXISTS "Appointment_propertyId_idx" ON "appointments" ("propertyId");
CREATE INDEX IF NOT EXISTS "Property_agentId_idx" ON "properties" ("agentId");
CREATE INDEX IF NOT EXISTS "Transaction_propertyId_idx" ON "transactions" ("propertyId");
CREATE INDEX IF NOT EXISTS "EscrowAccount_transactionId_idx" ON "escrow_accounts" ("transactionId");

COMMIT;
