// AfriBayit — Certificate PDF Download API
// GET /api/academy/certificates/[id]/pdf — Download a certificate's PDF (with QR code)
//
// Streams the PDF directly to the client. The PDF is generated on-the-fly
// from the certificate row using the existing lib/certificates/generator.ts
// (pdfkit + qrcode). If the certificate has a cached pdfBase64 column, we
// stream that directly; otherwise we regenerate.
//
// The `[id]` param accepts either the Certificate.id (cuid) or the
// human-readable Certificate.certificateId (e.g. "AFB-C-...").
//
// Auth:
//   - The certificate's owner can always download their own.
//   - Anonymous downloads are allowed with ?token=<sha256(recipientName + certificateId)>
//     for public verification flows (the certificate viewer page uses this).
//   - Otherwise, 401.

import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { db } from '@/lib/db';
import {
  generateCertificatePDF,
  buildVerificationUrl,
} from '@/lib/certificates/generator';
import type { CertificateType } from '@/lib/certificates/templates';
import crypto from 'crypto';

export const dynamic = 'force-dynamic';

interface RouteContext {
  params: Promise<{ id: string }>;
}

export async function GET(request: NextRequest, { params }: RouteContext) {
  try {
    const { id: requestedId } = await params;

    if (!requestedId) {
      return NextResponse.json(
        { error: 'ID de certificat requis.' },
        { status: 400 }
      );
    }

    // Lookup by either id (cuid) or certificateId (human-readable)
    const certificate = await db.certificate.findFirst({
      where: {
        OR: [{ id: requestedId }, { certificateId: requestedId }],
      },
      include: {
        user: { select: { id: true, name: true } },
        course: { select: { title: true, instructor: true } },
      },
    });

    if (!certificate) {
      return NextResponse.json(
        { error: 'Certificat introuvable.' },
        { status: 404 }
      );
    }

    // Auth check
    const session = await getServerSession(authOptions);
    const sessionUserId = session?.user
      ? ((session.user as Record<string, unknown>).id as string | undefined)
      : undefined;

    // Verify the access token (for anonymous / public verification links)
    const { searchParams } = new URL(request.url);
    const accessToken = searchParams.get('token');
    const expectedToken = crypto
      .createHash('sha256')
      .update(`${certificate.recipientName}:${certificate.certificateId}`)
      .digest('hex');

    const isOwner = sessionUserId === certificate.userId;
    const isAdmin = session?.user
      ? ((session.user as Record<string, unknown>).role as string) === 'admin'
      : false;
    const hasValidToken = accessToken && accessToken === expectedToken;

    if (!isOwner && !isAdmin && !hasValidToken) {
      return NextResponse.json(
        { error: 'Accès non autorisé à ce certificat.' },
        { status: 401 }
      );
    }

    // 1. Try the cached pdfBase64 column (set when the certificate was first
    //    generated by lib/certificates/index.ts::generateCertificate).
    if (certificate.pdfBase64) {
      try {
        const buffer = Buffer.from(certificate.pdfBase64, 'base64');
        return streamPdf(buffer, certificate.certificateId);
      } catch (err) {
        console.warn(
          '[certificates/[id]/pdf] cached pdfBase64 decode failed — regenerating:',
          err
        );
      }
    }

    // 2. Regenerate the PDF on-the-fly using the existing generator
    const verificationUrl = buildVerificationUrl(certificate.certificateId);
    const dateStr = certificate.issuedAt.toLocaleDateString('fr-FR', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
    });

    let pdfBuffer: Buffer;
    try {
      pdfBuffer = await generateCertificatePDF({
        certificateId: certificate.certificateId,
        recipientName: certificate.recipientName,
        courseName: certificate.courseName,
        instructorName: certificate.instructorName,
        date: dateStr,
        type: (certificate.type as CertificateType) || 'course_completion',
        verificationUrl,
      });
    } catch (err) {
      // If pdfkit/qrcode aren't installed in this environment, fall back to
      // a JSON error response with a downloadUrl pointing at the verify route.
      console.error('[certificates/[id]/pdf] PDF generation failed:', err);
      return NextResponse.json(
        {
          error:
            'Génération PDF indisponible. Utilisez l\'URL de vérification pour consulter le certificat.',
          certificateId: certificate.certificateId,
          verificationUrl,
          recipientName: certificate.recipientName,
          courseName: certificate.courseName,
          instructorName: certificate.instructorName,
          issuedAt: certificate.issuedAt,
        },
        { status: 503 }
      );
    }

    // Cache the generated PDF back to the row so subsequent downloads are fast
    try {
      await db.certificate.update({
        where: { id: certificate.id },
        data: { pdfBase64: pdfBuffer.toString('base64') },
      });
    } catch (err) {
      // Non-fatal — the cache write may fail if the column is too large
      console.warn('[certificates/[id]/pdf] cache write failed (non-fatal):', err);
    }

    return streamPdf(pdfBuffer, certificate.certificateId);
  } catch (error) {
    console.error('[certificates/[id]/pdf] Error:', error);
    return NextResponse.json(
      { error: 'Erreur lors de la génération du PDF du certificat.' },
      { status: 500 }
    );
  }
}

function streamPdf(buffer: Buffer, certificateId: string): NextResponse {
  return new NextResponse(new Uint8Array(buffer), {
    status: 200,
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="certificat-afribayit-${certificateId}.pdf"`,
      'Cache-Control': 'private, no-cache, no-store, must-revalidate',
      'Content-Length': String(buffer.length),
    },
  });
}
